### ISSUE TITLE
El resultado de Stats() es incorrecto debido a valores repetidos

### ISSUE THREAD

**Issue by inrumi** [Darkensses/sofifa-psx-react#2]
https://github.com/Darkensses/sofifa-psx-react/blob/674c4b8be8dbf11542d035a8658003498b4e5718/src/api/mcr.js#L330

Indagando un poco en el codigo, me encontre con esta suma, intente reducir los valores de los parametros que vienen el objeto `player` pero me di cuenta que solo se suman ciertos valores.

Me gustaria resolver este issue, pero tambien quisiera saber si estos son todos los stats que se deben sumar de `player`

- offense
- defense
- bodyBalance
- stamina
- stamina ?
- speed
- acceleration
- passAccuracy
- shotPower
- shotAccuracy
- jumpPower
- headAccuracy
- technique
- dribble
- curve
- agression
- response

**Comment by Darkensses** [comment]
Gracias por levantar el Issue 🎈🐞 el stat de stamina debería sumarse una vez y no dos como actualmente está.

En cuanto a los stats que se deben de sumar son esos (son 16) y nada más. Esta formula esta estipulada en el documento de excel de polipoli. Añado captura solo para ilustrar.

Agradecería un PR eliminando el stat duplicado de stamina y los ajustes que sean necesarios.

Gracias!

![image](https://user-images.githubusercontent.com/23271049/66972496-685a9300-f05a-11e9-9a31-2279cb49c9d1.png)

![image](https://user-images.githubusercontent.com/23271049/66972520-7d372680-f05a-11e9-94dc-2119ace55a52.png)

**Comment by Diego-Pino** [comment]
Gracias @inrumi

**Comment by Darkensses** [comment]
Issue Resuelto en #3 🎉
