### ISSUE TITLE
Si se salva con solo 22 jugadores para los juegos que traen 22 players?

### ISSUE THREAD

**Issue by Diego-Pino** [Darkensses/sofifa-psx-react#4]
Hola buenos dias.

Primero para darte las gracias por tan maravilloso trabajo.... es una herramienta muy practica a la hora de editar el juego de we2002... te felicito por el manejo de nuevas tecnologias y el desarrollo de las mismas... realmente viendo la app se observa los beneficios de la nueva tecnología... y tu haz sido el único que ha conectado todo esos deseos de tener una app para editar la base de datos,  excelente trabajando.

Ahira tengo una pregunta:
Si observas los jugadores de we2002 son 23 y hay juegos que solo traen 22, sera posible descargar la .mcr con 22 players, asi quedaria un editor mas universal para todos los juegos de PlaysTation 1 era generacion , la PSX....

 yo creo que si... porque la api igual salva la informacion en mcr...

Bueno dejo esa pregunta por aca... muchas gracias, sigo estudiando el codigo... muy interesante...

Gracias por hacer este sueño realidad...

Bye

**Comment by Darkensses** [comment]
Hola @Diego-Pino 
Es posible guardar cualquier cantidad de jugadores siempre que no excedan los 23 :)
