### ISSUE TITLE
Can't acquire lock for an app:

### ISSUE THREAD

**Issue by Diego-Pino** [Darkensses/sofifa-psx-react#5]
**Can't acquire lock for an app.**
Este mensaje me sale cuando trato de cerrar la app en el sevidor de **Cpanel**.

**Anexo info**: 
"Can't acquire lock for an app:" error message, this probably means that some processes use the ".lock" file of your NodeJS application. This usually happens because a daemon script was previously started via NodeJS Selector -> Run NPM Script. When you start a script this way, you have no way of stopping it via UI.

![No puedo cerrar la app via Cpanel](https://i.ibb.co/3kg3ZsJ/Error-al-apagar-consola.png)

**Comment by Darkensses** [comment]
cerrado, ver #6
