### ISSUE TITLE
Run Script in CPanel

### ISSUE THREAD

**Issue by Diego-Pino** [Darkensses/sofifa-psx-react#6]
En Localhost funciona perfecto el script, pero en servidores cPanel no se entiende cual, script correr primero:
- Start
- Build
- Test
- Eject

![imagen](https://i.ibb.co/Yd5BqTC/Copia-run-script.png)

deberia este proceso estar mejor optimisado para servidores cPanel. asi al instalar el proceso sera mas facil.
en -Localhost- funciona perfecto

**Comment by Darkensses** [comment]
Cierro issue ya que eso corresponde al servicio para el deploy. Recomiendo usar netlify ya que es gratutio si tienes un repo en github, como este por ejemplo.
